Table Empresa {
  id integer [primary key]
  id_veiculo integer
  cpnj varchar(14) [not null]
  nome varchar(30) [not null]
}

Table Passageiro {
  id integer [primary key]
  nome varchar(200)
  cpf varchar(12) [not null]
}

Table Funcionario {
  id integer [primary key]
  nome varchar(200)
  cpf varchar(12)
  cnpj varchar(14)
  data_adimissao datetime [not null]
  data_demissao datetime [not null]
}

Table Motorista {
  id integer [primary key]
  id_funcionario integer [not null]
  cnh varchar(10) [not null]
}

Table Cobrador {
  id integer [primary key]
  id_funcionario integer [not null]
}

Table PassageiroCartao{
  id integer [primary key]
  id_passageiro integer [not null]
  id_cartao integer [not null]
}

Table Cartao {
  id integer [primary key]
  numero varchar(16) [not null]
  status_cartao varchar(20) [not null]
  id_empresa_responsavel integer [not null]
  id_tipo_passagem integer [not null]
}

Table Passagem{
  id integer [primary key]
  id_cartao integer
  flag_a_vista bit
  flag_integracao bit
}

Table TipoPassagem {
  id integer [primary key]
  valor float [not null]
  descricao varchar(100) [not null]
}

Table Veiculo {
  id integer [primary key]
  modelo varchar(16) [not null]
  placa varchar(7) [not null]
}

Table RegistroTurnoVeiculo{
  id integer [primary key]
  id_veiculo integer [not null]
  id_motorista integer [not null]
  id_cobrador integer [not null]
  id_linha integer [not null]
  data_horario_entrada datetime [not null]
  data_horario_saida datetime
}

Table Linha {
  id integer [primary key]
  idItinerario integer
  horario datetime
  codigo integer
  nome varchar(200)
}

Table Itinerario {
  id integer [primary key]
  id_endereco_saida integer [not null]
  id_endereco_chegada integer [not null]
}

Table Endereco{
  id integer [primary key]
  cep varchar(8) [not null]
  rua varchar(100) [not null]
  id_bairro integer [not null]
}

Table Localizacao{
  id integer [primary key]
  id_endereco integer [not null]
  latitude float [not null]
  longitude float [not null]
}

Table Bairro {
  id integer [primary key]
  nome varchar(100)
  estado varchar(2) [not null]
  cidade varchar(100) [not null]
}

Table Estacao {
  id integer [primary key]
  id_localizacao integer [not null]
  id_plataforma integer [not null]
  nome varchar(100) [not null]
}

Table Plataforma{
  id integer [primary key]
  id_linha integer [not null]
  codigo varchar(1) [not null]
}

Table Ponto {
  id integer [primary key]
  id_localizacao integer [not null]
}

Table ItinerarioPonto {
  id_itinerario integer [primary key]
  id_ponto integer [primary key]
  id integer
  ordem integer
}

Table Consorcio {
  id integer [primary key]
  id_empresa integer 
  id_linha integer
}

Table Viagem {
  id integer [primary key]
  id_ponto_saida integer [not null]
  id_ponto_chegada integer [not null]
  id_passagem integer [not null]
  id_registro_turno_veiculo integer [not null]
  id_passageiro integer [not null]
  id_linha integer [not null]
  data_horario_saida datetime
  data_horario_chegada datetime
}

Ref: Motorista.id_funcionario - Funcionario.id
Ref: Cobrador.id_funcionario - Funcionario.id
Ref: PassageiroCartao.id_passageiro > Passageiro.id
Ref: PassageiroCartao.id_cartao - Cartao.id
Ref: Cartao.id_empresa_responsavel > Empresa.id
Ref: Cartao.id_tipo_passagem > TipoPassagem.id
Ref: Empresa.id_veiculo < Veiculo.id
Ref: Passagem.id_cartao > Cartao.id
Ref: RegistroTurnoVeiculo.id_veiculo > Veiculo.id
Ref: RegistroTurnoVeiculo.id_motorista > Motorista.id
Ref: RegistroTurnoVeiculo.id_cobrador > Cobrador.id
Ref: RegistroTurnoVeiculo.id_linha > Linha.id
Ref: Linha.idItinerario < Itinerario.id
Ref: Itinerario.id_endereco_saida > Endereco.id
Ref: Itinerario.id_endereco_chegada > Endereco.id
Ref: Endereco.id_bairro > Bairro.id
Ref: Localizacao.id_endereco > Endereco.id
Ref: Estacao.id_localizacao < Localizacao.id
Ref: Estacao.id_plataforma < Plataforma.id
Ref: Plataforma.id_linha < Linha.id
Ref: Ponto.id_localizacao - Localizacao.id
Ref: Consorcio.id_empresa < Empresa.id
Ref: Consorcio.id_linha < Linha.id
Ref: Viagem.id_ponto_saida > Ponto.id
Ref: Viagem.id_ponto_chegada > Ponto.id
Ref: Viagem.id_passagem - Passagem.id
Ref: Viagem.id_registro_turno_veiculo > RegistroTurnoVeiculo.id
Ref: Viagem.id_passageiro > Passageiro.id
Ref: Viagem.id_linha > Linha.id
Ref: Itinerario.id < ItinerarioPonto.id_itinerario
Ref: Ponto.id > ItinerarioPonto.id_ponto
