Table Empresa {
  id integer [primary key]
  nome varchar(30)
}

Table Passageiro {
  id integer [primary key]
  nome varchar(200)
  cpf varchar(12) [not null]
}

Table Funcionario {
  id integer [primary key]
  nome varchar(200)
  cpf varchar(12)
  cnpj varchar(14)
  data_adimissao datetime [not null]
  data_demissao datetime [not null]
}

Table Motorista {
  id integer [primary key]
  id_funcionario integer [not null]
  cnh varchar(10) [not null]
}

Table Cobrador {
  id integer [primary key]
  id_funcionario integer [not null]
}

Table Cartao {
  id integer [primary key]
  numero varchar(16) [not null]
  id_tipo_cartao integer [not null]
  id_empresa_responsavel integer [not null]
}

Table TipoCartao{
  id integer [primary key]
  descricao varchar(100) [not null]
}

Table tipoPassagem {
  valor float
}

Table Veiculo {
  placa varchar(7)
}

Table Linha {
  idItinerario integer
}

Table Itinerario {
  id integer [primary key]
}

Table Bairro {
  nome varchar(100)
}

Table Estacao {
  nome varchar(100)
}

Table Ponto {
  seila varchar(100)
}

Table Passagem {
  naoseitambem varchar(100)
}

Table TipoPassagem {
  nome varchar(10)
}

Table Consorcio {
  consorcios a
}

Table Viagem {
  saida varchar(100)
  chegada varchar(100)
}
